# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import BookStore_pb2 as BookStore__pb2


class BooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/BookStore.Books/GetBook',
                request_serializer=BookStore__pb2.GetBookRequest.SerializeToString,
                response_deserializer=BookStore__pb2.GetBookResponse.FromString,
                )
        self.GetBookById = channel.unary_unary(
                '/BookStore.Books/GetBookById',
                request_serializer=BookStore__pb2.GetBookByIdRequest.SerializeToString,
                response_deserializer=BookStore__pb2.GetBookByIdResponse.FromString,
                )
        self.AddBook = channel.unary_unary(
                '/BookStore.Books/AddBook',
                request_serializer=BookStore__pb2.AddBookRequest.SerializeToString,
                response_deserializer=BookStore__pb2.AddBookResponse.FromString,
                )
        self.UpdateBook = channel.unary_unary(
                '/BookStore.Books/UpdateBook',
                request_serializer=BookStore__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=BookStore__pb2.UpdateBookResponse.FromString,
                )
        self.DeleteBook = channel.unary_unary(
                '/BookStore.Books/DeleteBook',
                request_serializer=BookStore__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=BookStore__pb2.DeleteBookResponse.FromString,
                )


class BooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=BookStore__pb2.GetBookRequest.FromString,
                    response_serializer=BookStore__pb2.GetBookResponse.SerializeToString,
            ),
            'GetBookById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookById,
                    request_deserializer=BookStore__pb2.GetBookByIdRequest.FromString,
                    response_serializer=BookStore__pb2.GetBookByIdResponse.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=BookStore__pb2.AddBookRequest.FromString,
                    response_serializer=BookStore__pb2.AddBookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=BookStore__pb2.UpdateBookRequest.FromString,
                    response_serializer=BookStore__pb2.UpdateBookResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=BookStore__pb2.DeleteBookRequest.FromString,
                    response_serializer=BookStore__pb2.DeleteBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookStore.Books', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Books(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore.Books/GetBook',
            BookStore__pb2.GetBookRequest.SerializeToString,
            BookStore__pb2.GetBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore.Books/GetBookById',
            BookStore__pb2.GetBookByIdRequest.SerializeToString,
            BookStore__pb2.GetBookByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore.Books/AddBook',
            BookStore__pb2.AddBookRequest.SerializeToString,
            BookStore__pb2.AddBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore.Books/UpdateBook',
            BookStore__pb2.UpdateBookRequest.SerializeToString,
            BookStore__pb2.UpdateBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore.Books/DeleteBook',
            BookStore__pb2.DeleteBookRequest.SerializeToString,
            BookStore__pb2.DeleteBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
